insert into Themes(name, description, picture) values('Europe', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQQqSHfpw2SSa5cl1IsR_y8KPjIKiRFA1OW5uH6fyBkDzxUiv41&usqp=CAU');
insert into Themes(name, description, picture) values('Africa', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...', 'https://wallpaperaccess.com/full/362147.jpg');
insert into Themes(name, description, picture) values('North America', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...', 'https://elenarts.ch/wp-content/uploads/2017/04/canada_Niagara_falls_from_far_with_blue_cloud_and_buildings_web.jpg');
insert into Themes(name, description, picture) values('South America', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...', 'https://cdn.hipwallpaper.com/i/28/15/RZTMSP.jpg');
insert into Themes(name, description, picture) values('Asia', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...', 'https://c4.wallpaperflare.com/wallpaper/30/70/460/japan-japan-mountain-mount-fuji-wallpaper-preview.jpg');
insert into Themes(name, description, picture) values('Australia', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...', 'https://wallpaperaccess.com/full/889209.png');

insert into Articles(title, file_name, description, text, tag, theme_id) values('France','fox.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'City', 1);
insert into Articles(title, file_name, description, text, tag, theme_id) values('Spain','fox.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Sea', 1);
insert into Articles(title, file_name, description, text, tag, theme_id) values('Lithuania','fox.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'City', 1);

insert into Articles(title, file_name, description, text, tag, theme_id) values('Egypt','fox.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Desert', 2);
insert into Articles(title, file_name, description, text, tag, theme_id) values('Arab Emirates','fox.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Luxury', 2);
insert into Articles(title, file_name, description, text, tag, theme_id) values('Kenya','fox.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Wild-life', 2);

insert into Articles(title, file_name, description, text, tag, theme_id) values('Canada','fox.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Winter', 3);
insert into Articles(title, file_name, description, text, tag, theme_id) values('Texas','fox.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Hot', 3);
insert into Articles(title, file_name, description, text, tag, theme_id) values('San Francisco','fox.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Beaches', 3);

insert into Articles(title, file_name, description, text, tag, theme_id) values('Brazil','fox.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'City', 4);
insert into Articles(title, file_name, description, text, tag, theme_id) values('Argentina','fox.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Desert', 4);
insert into Articles(title, file_name, description, text, tag, theme_id) values('Peru','fox.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Desert', 4);

insert into Articles(title, file_name, description, text, tag, theme_id) values('Japan','fox.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Forest', 5);
insert into Articles(title, file_name, description, text, tag, theme_id) values('India','fox.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Sea', 5);
insert into Articles(title, file_name, description, text, tag, theme_id) values('New Zealand','fox.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Forest', 5);

insert into Articles(title, file_name, description, text, tag, theme_id) values('Adelaide','fox.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Mountains', 6);
insert into Articles(title, file_name, description, text, tag, theme_id) values('Brisbane','fox.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Desert', 6);
insert into Articles(title, file_name, description, text, tag, theme_id) values('Canberra','fox.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...', 'Desert', 6);

insert into Trips(article_id, file_name, location, price, description, days) values(1,'fox.jpg', 'Paris', 599.99, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consecteturcursus imperdiet', 6);
insert into Trips(article_id, file_name, location, price, description, days) values(2,'fox.jpg', 'New York', 450.99, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consecteturcursus imperdiet', 7);
insert into Trips(article_id, file_name, location, price, description, days) values(3,'fox.jpg', 'Hawaii', 1699.99, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consecteturcursus imperdiet', 10);
insert into Trips(article_id, file_name, location, price, description, days) values(4,'fox.jpg', 'London', 300.99, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at sem eget diam pellentesque porttitor. Etiam id tellus ut nibh cursus imperdiet...Lorem ipsum dolor sit amet, consecteturcursus imperdiet', 14);


insert into Users(user_id, username, password, First_name, Last_name, Email)
    values(1, 'user', '{bcrypt}$2y$12$A7x.2lPxE6YdV8ed6OYbDucRiod32wqMF9JNerE.wq4glQWaIjRnO', 'Johns', 'Doesss', 'rimastatt@gmail.com');
insert into Users(user_id, username, password, First_name, Last_name, Email)
    values(2, 'admin', '{bcrypt}$2y$12$A7x.2lPxE6YdV8ed6OYbDucRiod32wqMF9JNerE.wq4glQWaIjRnO', 'Jackz', 'Sparrowsss', 'admin@adming.com');

insert into Roles(role_id, role) values(1, 'CUSTOMER');
insert into Roles(role_id, role) values(2, 'ADMIN');

insert into Users_Roles(user_id, role_id) values(1, 1);
insert into Users_Roles(user_id, role_id) values(2, 2);